import axios from 'axios';
import { Email } from '@prisma/client';

export class SlackNotifier {
  private static getWebhookUrl(): string {
    const url = process.env.SLACK_WEBHOOK_URL;
    if (
      !url ||
      url.trim() === '' ||
      url.includes('your_test_webhook_url_here')
    ) {
      throw new Error(
        'SLACK_WEBHOOK_URL environment variable is not configured.'
      );
    }
    return url.trim();
  }

  /**
   * Sends a notification to a Slack channel via Webhook using Block Kit.
   * Formats the email summary, subject, category, and metadata to indicate it came from InboxOS AI.
   *
   * @param email The ingested Email object from Prisma
   * @param summary Optional AI summary of the email. If not provided, a body snippet is used.
   * @returns Promise<boolean> indicating whether the notification was sent successfully
   */
  public static async sendEmailNotification(
    email: Email,
    summary?: string
  ): Promise<boolean> {
    try {
      const webhookUrl = this.getWebhookUrl();

      // Fallback values for empty/null fields
      const subject = email.subject?.trim() || '(No Subject)';
      const category = email.category?.trim() || 'Unclassified';
      const sender = email.sender || 'Unknown Sender';
      const recipient = email.recipient || 'Unknown Recipient';

      // Determine the summary text to display
      let summaryText = summary?.trim();
      if (!summaryText) {
        summaryText = email.body
          ? email.body.length > 250
            ? email.body.substring(0, 247) + '...'
            : email.body
          : '(Empty Body)';
      }

      // Format Slack Block Kit Payload
      const payload = {
        text: `InboxOS AI: New Email - ${subject}`, // Fallback text for notifications/watch apps
        blocks: [
          {
            type: 'header',
            text: {
              type: 'plain_text',
              text: '🤖 InboxOS AI Notification',
              emoji: true,
            },
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: '*New Email Ingested and Processed by AI*',
            },
          },
          {
            type: 'divider',
          },
          {
            type: 'section',
            fields: [
              {
                type: 'mrkdwn',
                text: `*Subject:*\n${subject}`,
              },
              {
                type: 'mrkdwn',
                text: `*AI Category:*\n\`${category}\``,
              },
              {
                type: 'mrkdwn',
                text: `*Sender:*\n${sender}`,
              },
              {
                type: 'mrkdwn',
                text: `*Recipient:*\n${recipient}`,
              },
            ],
          },
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: `*AI Summary / Key Content:*\n${summaryText}`,
            },
          },
          {
            type: 'divider',
          },
          {
            type: 'context',
            elements: [
              {
                type: 'mrkdwn',
                text: `💼 Generated by *InboxOS AI Engine* • ID: \`${email.id}\``,
              },
            ],
          },
        ],
      };

      console.log(
        `Sending Slack Block Kit notification for email: "${subject}"`
      );

      const response = await axios.post(webhookUrl, payload, {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 10000, // 10s timeout
      });

      if (response.status >= 200 && response.status < 300) {
        console.log('Slack notification sent successfully.');
        return true;
      } else {
        console.error(
          `Failed to send Slack notification. Status code: ${response.status}`
        );
        return false;
      }
    } catch (error: any) {
      console.error('Error sending Slack notification:');
      if (axios.isAxiosError(error)) {
        if (error.response) {
          console.error(`  Status: ${error.response.status}`);
          console.error(`  Data: ${JSON.stringify(error.response.data)}`);
        } else if (error.request) {
          console.error('  No response received from Slack server.');
        } else {
          console.error(`  Request setup error: ${error.message}`);
        }
      } else {
        console.error(`  Unknown error: ${error.message || error}`);
      }
      return false;
    }
  }
}
